[mypy]

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-typer.*]
ignore_missing_imports = True

[mypy-drfp,drfp.*]
ignore_missing_imports = True

[mypy-sklearn,sklearn.*]
ignore_missing_imports = True

[mypy-umap,umap.*]
ignore_missing_imports = True

[mypy-linkml_store,linkml_store.*]
ignore_missing_imports = True

[mypy-linkml_embeddings_explorer,linkml_embeddings_explorer.*]
ignore_missing_imports = True

[mypy-duckdb,duckdb.*]
ignore_missing_imports = True

[mypy-llm,llm.*]
ignore_missing_imports = True

[mypy-xgboost,xgboost.*]
ignore_missing_imports = True
