"""Tests for citation-backed classifier research helpers."""

from pathlib import Path

import pytest

from autarch.classification_research import (
    AUTOGENERATED_EVIDENCE_HEADER,
    ClassificationResearchRecord,
    ReactionClassMetadata,
    collect_reaction_class_metadata,
    extract_research_record,
    merge_docstring_with_evidence,
    parse_key_value_options,
    replace_class_docstring,
)


def test_parse_key_value_options_parses_scalars() -> None:
    """Provider params should accept YAML-like scalar values."""
    parsed = parse_key_value_options(
        ["temperature=0.1", "use_cache=true", "label=kinase"]
    )

    assert parsed == {
        "temperature": 0.1,
        "use_cache": True,
        "label": "kinase",
    }


def test_parse_key_value_options_rejects_missing_equals() -> None:
    """Malformed key-value options should fail early."""
    with pytest.raises(ValueError, match="Expected key=value"):
        parse_key_value_options(["temperature"])


def test_collect_reaction_class_metadata_kinase() -> None:
    """Known classifiers should resolve to concrete source metadata."""
    metadata = collect_reaction_class_metadata("Kinase")

    assert metadata.class_name == "Kinase"
    assert metadata.module_name == "autarch.ontology.kinase"
    assert metadata.source_path.endswith("src/autarch/ontology/kinase.py")
    assert metadata.go_id == "GO:0016301"
    assert metadata.ec_number_prefix == "2.7.-.-"


def test_extract_research_record_from_markdown() -> None:
    """The research report parser should extract the fenced YAML payload."""
    metadata = ReactionClassMetadata(
        class_name="Kinase",
        module_name="autarch.ontology.kinase",
        source_path="src/autarch/ontology/kinase.py",
        go_id="GO:0016301",
        go_label="kinase activity",
        go_definition="Catalysis of phosphate transfer.",
        ec_number_prefix="2.7.-.-",
        current_docstring="Kinase classifier.",
    )
    markdown = """
Research report

```yaml
class_name: Kinase
module_name: autarch.ontology.kinase
source_path: src/autarch/ontology/kinase.py
question: How is Kinase defined classification-wise?
go_id: GO:0016301
go_label: kinase activity
go_definition: Catalysis of phosphate transfer.
ec_number_prefix: 2.7.-.-
evidence:
  - reference_id: DOI:10.1000/kinase
    reference_title: Example Kinase Review
    supporting_text: Kinases transfer phosphate groups from ATP to acceptor molecules.
```
"""

    record = extract_research_record(markdown, metadata)

    assert isinstance(record, ClassificationResearchRecord)
    assert record.class_name == "Kinase"
    assert record.evidence[0].reference_id == "DOI:10.1000/kinase"


def test_merge_docstring_with_evidence_replaces_existing_section() -> None:
    """Reapplying evidence should replace the old autogenerated block."""
    record = ClassificationResearchRecord.model_validate(
        {
            "class_name": "Kinase",
            "module_name": "autarch.ontology.kinase",
            "source_path": "src/autarch/ontology/kinase.py",
            "question": "How is Kinase defined classification-wise?",
            "go_id": "GO:0016301",
            "ec_number_prefix": "2.7.-.-",
            "evidence": [
                {
                    "reference_id": "DOI:10.1000/kinase",
                    "reference_title": "Example Kinase Review",
                    "supporting_text": "Kinases transfer phosphate groups from ATP to acceptor molecules.",
                }
            ],
        }
    )
    current_docstring = (
        "Kinase classifier.\n\n"
        f"{AUTOGENERATED_EVIDENCE_HEADER}\n"
        '- "Old evidence" [DOI:old]'
    )

    merged = merge_docstring_with_evidence(current_docstring, record)

    assert merged.count(AUTOGENERATED_EVIDENCE_HEADER) == 1
    assert "Old evidence" not in merged
    assert "DOI:10.1000/kinase" in merged


def test_replace_class_docstring_updates_source(tmp_path: Path) -> None:
    """Docstring replacement should preserve valid Python source."""
    source_path = tmp_path / "demo_classifier.py"
    source_path.write_text(
        'class DemoClassifier:\n'
        '    """Original summary.\n'
        '\n'
        '    Existing details.\n'
        '    """\n'
        '\n'
        '    pass\n',
        encoding="utf-8",
    )

    new_docstring = (
        "Updated summary.\n\n"
        "Validated literature evidence:\n"
        '- "Exact excerpt." [DOI:10.1000/demo]'
    )
    replace_class_docstring(source_path, "DemoClassifier", new_docstring)
    updated = source_path.read_text(encoding="utf-8")

    assert "Updated summary." in updated
    assert "DOI:10.1000/demo" in updated
    compile(updated, str(source_path), "exec")

