"""Citation-backed research workflow for classifier documentation."""

from __future__ import annotations

import ast
from dataclasses import asdict, dataclass
from inspect import getdoc
import inspect
import json
from pathlib import Path
import re
import sys
import textwrap
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field
import yaml

from autarch.classifier import ReactionClassifier


AUTOGENERATED_EVIDENCE_HEADER = "Validated literature evidence:"
YAML_BLOCK_RE = re.compile(r"```yaml\s*(.*?)```", re.IGNORECASE | re.DOTALL)


class EvidenceSnippet(BaseModel):
    """Exact text evidence for a classifier definition."""

    model_config = ConfigDict(extra="forbid")

    reference_id: str = Field(min_length=1)
    reference_title: str = Field(min_length=1)
    supporting_text: str = Field(min_length=1)


class ClassificationResearchRecord(BaseModel):
    """Structured research output for a reaction classifier."""

    model_config = ConfigDict(extra="forbid")

    class_name: str = Field(min_length=1)
    module_name: str = Field(min_length=1)
    source_path: str = Field(min_length=1)
    question: str = Field(min_length=1)
    go_id: Optional[str] = None
    go_label: Optional[str] = None
    go_definition: Optional[str] = None
    ec_number_prefix: Optional[str] = None
    evidence: list[EvidenceSnippet] = Field(min_length=1)


@dataclass(frozen=True)
class ReactionClassMetadata:
    """Metadata required to research a classifier."""

    class_name: str
    module_name: str
    source_path: str
    go_id: Optional[str]
    go_label: Optional[str]
    go_definition: Optional[str]
    ec_number_prefix: Optional[str]
    current_docstring: str


@dataclass(frozen=True)
class ResearchArtifactPaths:
    """Filesystem locations for generated research artifacts."""

    class_dir: Path
    query_path: Path
    report_path: Path
    record_path: Path
    validation_path: Path


@dataclass(frozen=True)
class EvidenceValidationResult:
    """Validation outcome for a single evidence item."""

    index: int
    reference_id: str
    reference_title: str
    supporting_text: str
    is_valid: bool
    message: str


def parse_key_value_options(values: Optional[list[str]]) -> dict[str, Any]:
    """Parse repeated ``key=value`` CLI options into a dictionary."""
    if not values:
        return {}

    parsed: dict[str, Any] = {}
    for value in values:
        if "=" not in value:
            raise ValueError(f"Expected key=value, got: {value}")
        key, raw_value = value.split("=", 1)
        key = key.strip()
        if not key:
            raise ValueError(f"Missing key in option: {value}")
        parsed[key] = yaml.safe_load(raw_value)
    return parsed


def collect_reaction_class_metadata(
    class_name: str,
    cache_dir: str | Path = "cache",
) -> ReactionClassMetadata:
    """Collect classifier metadata used to drive literature research."""
    classifier = ReactionClassifier()
    if class_name not in classifier.reaction_classes:
        available = ", ".join(sorted(classifier.reaction_classes))
        raise ValueError(f"Unknown reaction class '{class_name}'. Available classes: {available}")

    cls = classifier.reaction_classes[class_name]
    go_id = getattr(cls, "GO_ID", None)
    go_label = None
    go_definition = None
    if go_id:
        go_label, go_definition = _lookup_go_metadata(go_id, Path(cache_dir))

    return ReactionClassMetadata(
        class_name=cls.__name__,
        module_name=cls.__module__,
        source_path=_normalize_source_path(inspect.getfile(cls)),
        go_id=go_id,
        go_label=go_label,
        go_definition=go_definition,
        ec_number_prefix=getattr(cls, "EC_NUMBER_PREFIX", None),
        current_docstring=getdoc(cls) or "",
    )


def build_research_prompt(
    metadata: ReactionClassMetadata,
    evidence_count: int = 3,
) -> str:
    """Build a structured deep-research prompt for one classifier."""
    details = [
        f"- Class name: {metadata.class_name}",
        f"- Module: {metadata.module_name}",
        f"- Source file: {metadata.source_path}",
        f"- GO ID: {metadata.go_id or 'None'}",
        f"- GO label: {metadata.go_label or 'Unavailable'}",
        f"- GO definition: {metadata.go_definition or 'Unavailable'}",
        f"- EC number prefix: {metadata.ec_number_prefix or 'None'}",
    ]
    current_doc = metadata.current_docstring or "No current docstring is present."
    return textwrap.dedent(
        f"""
        Research the biochemical classification basis for the Autarch reaction classifier `{metadata.class_name}`.

        Current classifier metadata:
        {chr(10).join(details)}

        Current class docstring:
        ```text
        {current_doc}
        ```

        Focus on literature or authoritative database/update papers that define or bound this reaction class classification-wise.
        Prefer IUBMB/EC nomenclature papers, GO/Rhea/UniProt database papers, and well-cited biochemical reviews.

        Return a markdown report that includes exactly one fenced YAML block labelled `yaml`.
        The YAML must conform to this schema:

        ```yaml
        class_name: "{metadata.class_name}"
        module_name: "{metadata.module_name}"
        source_path: "{metadata.source_path}"
        question: "How is {metadata.class_name} defined classification-wise?"
        go_id: "{metadata.go_id or ''}"
        go_label: "{metadata.go_label or ''}"
        go_definition: "{metadata.go_definition or ''}"
        ec_number_prefix: "{metadata.ec_number_prefix or ''}"
        evidence:
          - reference_id: "DOI:10.xxxx/xxxxx"
            reference_title: "Exact title of the paper or review"
            supporting_text: "A short exact excerpt from the source supporting the class definition"
        ```

        Constraints:
        - Include between 2 and {evidence_count} evidence entries.
        - `supporting_text` must be an exact excerpt, not a paraphrase.
        - Keep each `supporting_text` short enough to live in a Python docstring.
        - Use DOI identifiers whenever possible. Use PMID only when DOI is unavailable.
        - Do not fabricate titles, identifiers, or quotes.
        - After the YAML block, add a short prose note summarizing the class definition consensus.
        """
    ).strip()


def run_deep_research(
    prompt: str,
    provider: Optional[str] = None,
    model: Optional[str] = None,
    provider_params: Optional[dict[str, Any]] = None,
) -> Any:
    """Run deep research lazily so normal classification usage stays lightweight."""
    if sys.version_info < (3, 12):
        raise RuntimeError(
            "Deep research requires Python 3.12+ because `deep-research-client` "
            "is only installed for that interpreter range. Run "
            "`uv run --python 3.12 autarch research-class ...`."
        )

    try:
        from deep_research_client import DeepResearchClient  # type: ignore[import-not-found, import-untyped]
    except ImportError as exc:  # pragma: no cover - depends on runtime environment
        raise RuntimeError(
            "`deep-research-client` is not available in the active environment. "
            "Run `uv sync` and invoke the command with `uv run --python 3.12 ...`."
        ) from exc

    client = DeepResearchClient()
    return client.research(
        query=prompt,
        provider=provider,
        model=model,
        provider_params=provider_params or None,
    )


def extract_research_record(
    markdown: str,
    metadata: ReactionClassMetadata,
) -> ClassificationResearchRecord:
    """Extract the YAML payload from a research report."""
    matches = YAML_BLOCK_RE.findall(markdown)
    for block in matches:
        payload = yaml.safe_load(block)
        if not isinstance(payload, dict):
            continue
        payload.setdefault("class_name", metadata.class_name)
        payload.setdefault("module_name", metadata.module_name)
        payload.setdefault("source_path", metadata.source_path)
        payload.setdefault(
            "question",
            f"How is {metadata.class_name} defined classification-wise?",
        )
        payload.setdefault("go_id", metadata.go_id)
        payload.setdefault("go_label", metadata.go_label)
        payload.setdefault("go_definition", metadata.go_definition)
        payload.setdefault("ec_number_prefix", metadata.ec_number_prefix)
        record = ClassificationResearchRecord.model_validate(payload)
        _assert_metadata_alignment(record, metadata)
        return record
    raise ValueError("Deep research output did not contain a valid fenced YAML block.")


def artifact_paths(
    metadata: ReactionClassMetadata,
    output_dir: str | Path,
) -> ResearchArtifactPaths:
    """Return canonical paths for the research artifacts of one class."""
    base_dir = Path(output_dir) / Path(metadata.source_path).stem
    return ResearchArtifactPaths(
        class_dir=base_dir,
        query_path=base_dir / "query.md",
        report_path=base_dir / "report.md",
        record_path=base_dir / "evidence.yaml",
        validation_path=base_dir / "validation.json",
    )


def write_research_artifacts(
    metadata: ReactionClassMetadata,
    prompt: str,
    report_markdown: str,
    record: ClassificationResearchRecord,
    output_dir: str | Path,
) -> ResearchArtifactPaths:
    """Write prompt, raw report, and extracted evidence to disk."""
    paths = artifact_paths(metadata, output_dir)
    paths.class_dir.mkdir(parents=True, exist_ok=True)
    paths.query_path.write_text(prompt + "\n", encoding="utf-8")
    paths.report_path.write_text(report_markdown + "\n", encoding="utf-8")
    yaml_payload = yaml.safe_dump(
        record.model_dump(exclude_none=True),
        sort_keys=False,
        allow_unicode=False,
    )
    paths.record_path.write_text(yaml_payload, encoding="utf-8")
    return paths


def load_research_record(path: str | Path) -> ClassificationResearchRecord:
    """Load an extracted research record from YAML."""
    payload = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    return ClassificationResearchRecord.model_validate(payload)


def validate_research_record(
    record: ClassificationResearchRecord,
    cache_dir: str | Path = "references_cache",
) -> list[EvidenceValidationResult]:
    """Validate each exact quote using ``linkml-reference-validator``."""
    try:
        from linkml_reference_validator.models import (  # type: ignore[import-untyped]
            ReferenceValidationConfig,
        )
        from linkml_reference_validator.validation.supporting_text_validator import (  # type: ignore[import-untyped]
            SupportingTextValidator,
        )
    except ImportError as exc:  # pragma: no cover - depends on runtime environment
        raise RuntimeError(
            "`linkml-reference-validator` is not available in the active environment."
        ) from exc

    config = ReferenceValidationConfig(cache_dir=Path(cache_dir))
    validator = SupportingTextValidator(config)
    results: list[EvidenceValidationResult] = []
    for index, evidence in enumerate(record.evidence, start=1):
        result = validator.validate(
            evidence.supporting_text,
            evidence.reference_id,
            expected_title=evidence.reference_title,
            path=f"evidence[{index - 1}]",
        )
        results.append(
            EvidenceValidationResult(
                index=index,
                reference_id=evidence.reference_id,
                reference_title=evidence.reference_title,
                supporting_text=evidence.supporting_text,
                is_valid=result.is_valid,
                message=result.message,
            )
        )
    return results


def write_validation_report(
    record: ClassificationResearchRecord,
    results: list[EvidenceValidationResult],
    path: str | Path,
) -> None:
    """Persist validation outcomes for later inspection."""
    payload = {
        "class_name": record.class_name,
        "total": len(results),
        "valid": sum(1 for result in results if result.is_valid),
        "invalid": sum(1 for result in results if not result.is_valid),
        "results": [asdict(result) for result in results],
    }
    Path(path).write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def all_evidence_valid(results: list[EvidenceValidationResult]) -> bool:
    """Return ``True`` when every evidence item validated successfully."""
    return all(result.is_valid for result in results)


def merge_docstring_with_evidence(
    current_docstring: str,
    record: ClassificationResearchRecord,
) -> str:
    """Append a validated literature section to an existing docstring."""
    base = current_docstring.strip()
    if AUTOGENERATED_EVIDENCE_HEADER in base:
        base = base.split(AUTOGENERATED_EVIDENCE_HEADER, 1)[0].rstrip()

    evidence_lines = [AUTOGENERATED_EVIDENCE_HEADER]
    for evidence in record.evidence:
        evidence_lines.append(
            f'- "{evidence.supporting_text}" [{evidence.reference_id}]'
        )

    if base:
        return base + "\n\n" + "\n".join(evidence_lines)
    return "\n".join(evidence_lines)


def apply_research_record(record: ClassificationResearchRecord) -> Path:
    """Write validated evidence into the corresponding class docstring."""
    metadata = collect_reaction_class_metadata(record.class_name)
    if metadata.source_path != record.source_path:
        raise ValueError(
            f"Research record source path mismatch: {record.source_path} != {metadata.source_path}"
        )

    new_docstring = merge_docstring_with_evidence(metadata.current_docstring, record)
    target_path = Path(record.source_path)
    replace_class_docstring(target_path, record.class_name, new_docstring)
    return target_path


def replace_class_docstring(
    source_path: str | Path,
    class_name: str,
    new_docstring: str,
) -> None:
    """Replace the docstring of a class in-place."""
    path = Path(source_path)
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    class_node = _find_class_node(tree, class_name)
    if class_node is None:
        raise ValueError(f"Class '{class_name}' not found in {path}")

    doc_node = _find_docstring_node(class_node)
    if doc_node is None:
        raise ValueError(f"Class '{class_name}' does not have a docstring to replace")
    if (
        doc_node.lineno is None
        or doc_node.end_lineno is None
        or doc_node.end_col_offset is None
    ):
        raise ValueError(f"Could not determine docstring source range for {class_name}")

    start = _line_col_to_index(source, doc_node.lineno, doc_node.col_offset)
    end = _line_col_to_index(source, doc_node.end_lineno, doc_node.end_col_offset)
    indent = " " * doc_node.col_offset
    literal = _format_docstring_literal(new_docstring, indent)
    path.write_text(source[:start] + literal + source[end:], encoding="utf-8")


def _lookup_go_metadata(go_id: str, cache_dir: Path) -> tuple[Optional[str], Optional[str]]:
    """Look up GO metadata from the cached GO JSONL file when available."""
    go_terms_path = cache_dir / "go_terms.jsonl"
    if not go_terms_path.exists():
        return None, None

    with open(go_terms_path, encoding="utf-8") as handle:
        for line in handle:
            payload = json.loads(line)
            if payload.get("go_id") == go_id:
                return payload.get("label"), payload.get("definition")
    return None, None


def _normalize_source_path(path: str | Path) -> str:
    """Prefer repo-relative paths when the file lives under the current working tree."""
    resolved = Path(path).resolve()
    try:
        return str(resolved.relative_to(Path.cwd()))
    except ValueError:
        return str(resolved)


def _assert_metadata_alignment(
    record: ClassificationResearchRecord,
    metadata: ReactionClassMetadata,
) -> None:
    """Reject research payloads that drift away from the target class."""
    expected_pairs = {
        "class_name": metadata.class_name,
        "module_name": metadata.module_name,
        "source_path": metadata.source_path,
    }
    for field_name, expected in expected_pairs.items():
        actual = getattr(record, field_name)
        if actual != expected:
            raise ValueError(
                f"Research YAML {field_name} mismatch: expected {expected}, got {actual}"
            )


def _find_class_node(tree: ast.Module, class_name: str) -> Optional[ast.ClassDef]:
    """Find a class definition by name in a module AST."""
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            return node
    return None


def _find_docstring_node(class_node: ast.ClassDef) -> Optional[ast.Expr]:
    """Return the AST node that holds the class docstring."""
    if not class_node.body:
        return None
    candidate = class_node.body[0]
    if (
        isinstance(candidate, ast.Expr)
        and isinstance(candidate.value, ast.Constant)
        and isinstance(candidate.value.value, str)
    ):
        return candidate
    return None


def _line_col_to_index(source: str, line_number: int, column: int) -> int:
    """Convert a 1-based line and 0-based column into a string index."""
    lines = source.splitlines(keepends=True)
    return sum(len(line) for line in lines[: line_number - 1]) + column


def _format_docstring_literal(docstring: str, indent: str) -> str:
    """Render a multiline docstring literal aligned to the existing class body."""
    escaped = docstring.replace('"""', '\\"\\"\\"')
    lines = escaped.strip().splitlines()
    if not lines:
        return '""""""'
    if len(lines) == 1:
        return f'"""{lines[0]}"""'

    body = "\n".join(
        f"{indent}{line}" if line else indent
        for line in lines[1:]
    )
    return f'"""{lines[0]}\n{body}\n{indent}"""'
