"""acting on paired donors with incorporation or reduction of molecular oxygen."""

from autarch.ontology.ec_prefix_aggregate import ExplicitEcAggregate
from autarch.ontology.acting_on_paired_donors_with_incorporation_or_reduction_of_molecular_oxygen_miscellaneous import ActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenMiscellaneous
from autarch.ontology.acting_on_paired_donors_with_incorporation_or_reduction_of_molecular_oxygen_with_2_oxoglutarate_as_one_donor_and_the_other_dehydrogenated import ActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenWith2OxoglutarateAsOneDonorAndTheOtherDehydrogenated
from autarch.ontology.homomethionine_n_monooxygenase import HomomethionineNMonooxygenase
from autarch.ontology.limonene_12_monooxygenase import Limonene12Monooxygenase
from autarch.ontology.methylxanthine_n1_demethylase import MethylxanthineN1Demethylase
from autarch.ontology.methylxanthine_n3_demethylase import MethylxanthineN3Demethylase
from autarch.ontology.monocyclic_monoterpene_ketone_monooxygenase import MonocyclicMonoterpeneKetoneMonooxygenase
from autarch.ontology.nitroarene_dioxygenase import NitroareneDioxygenase
from autarch.ontology.oxidoreductase_acting_on_paired_donors_with_incorporation_or_reduction_of_molecular_oxygen_nadh_or_nadph_as_one_donor_and_incorporation_of_one_atom_of_oxygen import OxidoreductaseActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenNADHOrNADPHAsOneDonorAndIncorporationOfOneAtomOfOxygen
from autarch.ontology.oxidoreductase_acting_on_paired_donors_with_incorporation_or_reduction_of_molecular_oxygen_nadh_or_nadph_as_one_donor_and_incorporation_of_two_atoms_of_oxygen_into_one_donor import OxidoreductaseActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenNADHOrNADPHAsOneDonorAndIncorporationOfTwoAtomsOfOxygenIntoOneDonor
from autarch.ontology.oxidoreductase_acting_on_paired_donors_with_incorporation_or_reduction_of_molecular_oxygen_reduced_flavin_or_flavoprotein_as_one_donor_and_incorporation_of_one_atom_of_oxygen import OxidoreductaseActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenReducedFlavinOrFlavoproteinAsOneDonorAndIncorporationOfOneAtomOfOxygen
from autarch.ontology.oxidoreductase_acting_on_paired_donors_with_incorporation_or_reduction_of_molecular_oxygen_reduced_iron_sulfur_protein_as_one_donor_and_incorporation_of_one_atom_of_oxygen import OxidoreductaseActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenReducedIronSulfurProteinAsOneDonorAndIncorporationOfOneAtomOfOxygen
from autarch.ontology.oxidoreductase_acting_on_paired_donors_with_oxidation_of_a_pair_of_donors_resulting_in_the_reduction_of_molecular_oxygen_to_two_molecules_of_water import OxidoreductaseActingOnPairedDonorsWithOxidationOfAPairOfDonorsResultingInTheReductionOfMolecularOxygenToTwoMoleculesOfWater
from autarch.ontology.squalene_monooxygenase import SqualeneMonooxygenase
from autarch.ontology.two_oxoglutarate_dependent_dioxygenase import TwoOxoglutarateDependentDioxygenase
from autarch.ontology.vitamin_d3_24_hydroxylase import VitaminD324Hydroxylase


class ActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygen(ExplicitEcAggregate):
    """acting on paired donors with incorporation or reduction of molecular oxygen."""

    EC_NUMBER_PREFIX = '1.14.-.-'
    CHILD_CLASSES = (
        HomomethionineNMonooxygenase,
        Limonene12Monooxygenase,
        MethylxanthineN1Demethylase,
        MethylxanthineN3Demethylase,
        MonocyclicMonoterpeneKetoneMonooxygenase,
        NitroareneDioxygenase,
        SqualeneMonooxygenase,
        VitaminD324Hydroxylase,
        ActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenMiscellaneous,
        ActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenWith2OxoglutarateAsOneDonorAndTheOtherDehydrogenated,
        OxidoreductaseActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenNADHOrNADPHAsOneDonorAndIncorporationOfOneAtomOfOxygen,
        OxidoreductaseActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenNADHOrNADPHAsOneDonorAndIncorporationOfTwoAtomsOfOxygenIntoOneDonor,
        OxidoreductaseActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenReducedFlavinOrFlavoproteinAsOneDonorAndIncorporationOfOneAtomOfOxygen,
        OxidoreductaseActingOnPairedDonorsWithIncorporationOrReductionOfMolecularOxygenReducedIronSulfurProteinAsOneDonorAndIncorporationOfOneAtomOfOxygen,
        OxidoreductaseActingOnPairedDonorsWithOxidationOfAPairOfDonorsResultingInTheReductionOfMolecularOxygenToTwoMoleculesOfWater,
        TwoOxoglutarateDependentDioxygenase,
    )
