"""transmembrane transporter activity."""

from autarch.ontology.go_aggregate import ExplicitGoAggregate
from autarch.ontology.abc_type_carbohydrate_transporter import ABCTypeCarbohydrateTransporter
from autarch.ontology.abc_type_polar_amino_acid_transporter import ABCTypePolarAminoAcidTransporter
from autarch.ontology.atpase_coupled_transmembrane_transporter import ATPaseCoupledTransmembraneTransporter
from autarch.ontology.cytochrome_c_oxidase import CytochromeCOxidase
from autarch.ontology.primary_active_transmembrane_transporter import PrimaryActiveTransmembraneTransporter
from autarch.ontology.translocase_linked_to_hydrolysis import TranslocaseLinkedToHydrolysis
from autarch.ontology.translocation_of_amino_acids_and_peptides_linked_to_the_hydrolysis_of_a_nucleoside_triphosphate import TranslocationOfAminoAcidsAndPeptidesLinkedToTheHydrolysisOfANucleosideTriphosphate
from autarch.ontology.translocation_of_hydrons import TranslocationOfHydrons
from autarch.ontology.translocation_of_inorganic_anions_and_their_chelates_linked_to_the_hydrolysis_of_a_nucleoside_triphosphate import TranslocationOfInorganicAnionsAndTheirChelatesLinkedToTheHydrolysisOfANucleosideTriphosphate
from autarch.ontology.translocation_of_inorganic_cations_linked_to_the_hydrolysis_of_a_nucleoside_triphosphate import TranslocationOfInorganicCationsLinkedToTheHydrolysisOfANucleosideTriphosphate


class TransmembraneTransporterActivity(ExplicitGoAggregate):
    """transmembrane transporter activity."""

    GO_ID = "GO:0022857"
    CONCEPT_PHRASE = "transmembrane transporter activity"
    CHILD_CLASSES = (ATPaseCoupledTransmembraneTransporter, ABCTypeCarbohydrateTransporter, ABCTypePolarAminoAcidTransporter, PrimaryActiveTransmembraneTransporter, TranslocaseLinkedToHydrolysis, TranslocationOfHydrons, TranslocationOfInorganicCationsLinkedToTheHydrolysisOfANucleosideTriphosphate, TranslocationOfInorganicAnionsAndTheirChelatesLinkedToTheHydrolysisOfANucleosideTriphosphate, TranslocationOfAminoAcidsAndPeptidesLinkedToTheHydrolysisOfANucleosideTriphosphate, CytochromeCOxidase,)
